### ISSUE TITLE
http://<freeroute-host>:8080 403:Forbidden

### ISSUE THREAD

**Issue by wizarom** [admitrievsky/freeroute#2]
installed
changed dns settings
changed the gateway settings
when I try to log in to the webgui, I get 403: Forbidden

**Comment by admitrievsky** [comment]
try `http://<freeroute-host>:8080/index.html` as a workaround. Will be fixed in the near future

**Comment by admitrievsky** [comment]
Fixed https://github.com/admitrievsky/freeroute/pull/3
